[package]
name = "render_me_daddy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pixels = "0.13.0"
#winit = { version = "0.29.10", features = ["serde"] }
winit = "0.28.7"
chrono = "0.4.34"